# ---
# - name: Configure server and client
#   hosts: server:client
#   become: yes

#   tasks:
#     - name: Install and enable SSHD service
#       apt:
#         name: openssh-server
#         state: present
#       when: ansible_distribution == 'Ubuntu'

#     - name: Configure iptables on server
#       iptables:
#         chain: INPUT
#         policy: DROP
#         state: enabled
#       when: inventory_hostname == 'server'

#     - name: Allow incoming SSH on server
#       iptables:
#         chain: INPUT
#         protocol: tcp
#         destination_port: 22
#         jump: ACCEPT
#       when: inventory_hostname == 'server'

#     - name: Allow incoming HTTP on server
#       iptables:
#         chain: INPUT
#         protocol: tcp
#         destination_port: 80
#         jump: ACCEPT
#       when: inventory_hostname == 'server'

#     - name: Disable root SSH login
#       lineinfile:
#         path: /etc/ssh/sshd_config
#         regexp: '^PermitRootLogin'
#         line: 'PermitRootLogin no'
#         state: present
#       when: ansible_distribution == 'Ubuntu'

#     - name: Configure SSHD to block SSH brute force attacks
#       lineinfile:
#         path: /etc/ssh/sshd_config
#         regexp: '^MaxAuthTries'
#         line: 'MaxAuthTries 3'
#         state: present
#       when: ansible_distribution == 'Ubuntu'

# - name: Install text-based browser on client
#   hosts: client
#   become: yes

#   tasks:
#     - name: Install text-based browser (Lynx)
#       apt:
#         name: lynx
#         state: present
#       when: ansible_distribution == 'Ubuntu'
