# name: Wordpress destroy

# on:
#   push:
#     branches: [main]

# jobs:
#   destroy-infra:
#     runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: terraform init

      - name: Destroy Terraform Infrastructure
        id: destroy
        continue-on-error: true
        run: terraform destroy -auto-approve

      - name: Clean up SSH Key Pair
        run: |
          rm mykey-pair
          rm mykey-pair.pub
